# Generated by Django 3.1.4 on 2020-12-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/customers/'),
        ),
    ]
