# Generated by Django 3.1.4 on 2020-12-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_application_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='ammount',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='staff',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/staff/'),
        ),
    ]
