# Generated by Django 3.1.4 on 2020-12-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201224_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='education',
            field=models.CharField(blank=True, choices=[('Graduate', 'Graduate'), ('Not Graduate', 'Not Graduate')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='married',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='property_area',
            field=models.CharField(blank=True, choices=[('Rural', 'Rural'), ('Urban', 'Urban'), ('Semiurban', 'Semiurban')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='self_employed',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True),
        ),
    ]
